Repository akm-akm/xxx-bot, pull requests merged in 2021-10, with the labels that each got.

#4 Missing logo Fixed
  Readme.md
Labels: bug, hacktoberfest-accepted

#3 Update LICENSE
  LICENSE
Labels: hacktoberfest-accepted

#5 Update Readme.md
  Readme.md
Labels: documentation, hacktoberfest-accepted

#7 Edit readme
  Readme.md
Labels: documentation, hacktoberfest-accepted
